// V4L2EventWatcher.h - Subscribe to V4L2 events and forward them to Qt
// Minimal, single-file watcher that subscribes to V4L2_EVENT_CTRL and emits controlChanged(ctrlId, value)

#ifndef V4L2_EVENT_WATCHER_H
#define V4L2_EVENT_WATCHER_H

#include <QObject>
#include <QString>
#include <atomic>
#include <thread>

class V4L2EventWatcher : public QObject {
    Q_OBJECT
public:
    explicit V4L2EventWatcher(QObject *parent = nullptr);
    ~V4L2EventWatcher() override;

    // Start watching the given device (e.g., /dev/v4l-subdev3). Returns true if subscribed
    bool startWatching(const QString &devicePath);
    // Stop watching (blocking until thread joins)
    void stopWatching();
    bool isWatching() const;
    // Retrieve the last error message generated by this watcher (thread safe-ish read)
    QString lastError() const { return m_lastError; }

signals:
    void controlChanged(unsigned int controlId, int value);
    void errorOccurred(const QString &msg);

private:
    void runLoop();
    std::atomic_bool m_running{false};
    std::unique_ptr<std::thread> m_thread;
    int m_fd{-1};
    QString m_device;
    QString m_lastError;
};

#endif // V4L2_EVENT_WATCHER_H